watch_stylesheet: true
watch_config: true
debug: false
update_check: true

komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: "None"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 8
      left: 12
      bottom: -4
      right: 12
    widgets:
      left:
        - "home"
        - "weather"
      center:
        - "clock"
        - "komorebi_workspaces"
      right:
        - "media"
        - "volume"
        - "wallpapers"
widgets:
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "Tiling"
        floating_label: "Floating"
      app_icons: 
        enabled_populated: false
        enabled_active: false
        size: 12
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} - {title}"
      callbacks:
        on_left: "toggle_play_pause"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 35
        label_alt: 35
      hide_empty: true
      show_thumbnail: false
      controls_only: false
      controls_hide: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M}"
      label_alt: "{%A, %d %B %Y}"
      update_interval: 1000
      callbacks:
        on_left: "do_nothing"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>{level}"
      volume_icons:
        - "\ue74f" # Icon for muted
        - "\ue994" # Icon for 0-10% volume
        - "\ue994" # Icon for 11-30% volume
        - "\ue994" # Icon for 31-60% volume
        - "\ue994" # Icon for 61-100% volume
      audio_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "do_nothing"
        on_right: "toggle_mute"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "{temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: 'Get Your API Key From https://www.weatherapi.com'
      update_interval: 900 #Update interval in seconds, Min 600
      hide_decimal: true
      location: 'Dhaka'
      callbacks:
        on_left: "do_nothingl"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99" 
    
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\sifat\\Wallpapers"
      change_automatically: false
      update_interval: 60
      animation:
        enabled: true
        type: 'fadeInOut'
        duration: 200
      gallery:
        enabled: true
        blur: true
        image_width: 350
        image_per_page: 3
        show_buttons: false
        orientation: "landscape"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 5
        enable_cache: true
      callbacks:
        on_left: "toggle_gallery"
        on_middle: "do_nothing"
        on_right: "change_wallpaper"
      run_after: # List of functions to run after wallpaper is updated
        - "wal -s -t -e -q -n -i {image}" # Example command to run after wallpaper is updated
        - "cmd.exe /c start /min pwsh ./yasb.ps1" # Example command to run after wallpaper is updated
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "会"
      system_menu: true
      power_menu: false
      blur: false
      round_corners: false
      round_corners_type: "normal"
      distance: 5
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding: 
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
